FROM python:3

RUN pip --disable-pip-version-check install \
    coverage \
    ansible

ENV INSTALL_DIRECTORY=/fail2ban-ansible-modules
ENV PYTHONPATH=${INSTALL_DIRECTORY}

WORKDIR "${INSTALL_DIRECTORY}"
VOLUME "${INSTALL_DIRECTORY}"

CMD ["./run-tests.sh"]
